[package]
name = "num"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.6"

#[dependencies.fast-floats]
#git = 'https://github.com/unic0rn9k/fast-floats'
#optional = true

[features]
fast-floats = [] #["dep:fast-floats"]
default = ["fast-floats"]
